#!/usr/bin/env bash

# Install AWS binaries for edge/bastion/bot

curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
unzip awscli-bundle.zip
which python || ln -sf $(which python3) /usr/bin/python || exit 1

./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

aws --version

which wget || exit 1
wget "https://github.com/weaveworks/eksctl/releases/download/v0.82.0/eksctl_Linux_amd64.tar.gz"
mv eksctl_Linux_amd64.tar.gz /root/
cd /root
tar xzvf eksctl_Linux_amd64.tar.gz
mv /root/eksctl /usr/local/sbin/
chmod 0700 /usr/local/sbin/eksctl
